version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d
#      - data:/var/lib/mysql
#      - ./mysql:/var/lib/mysql

#volumes:
#  data: