spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc.swagger-ui.path: /swagger-ui.html

app:
  datasource:
    read-only:
      url: jdbc:mysql://localhost:3306/order_db
      username: readonly
      password: readonly

    write:
      url: jdbc:mysql://localhost:3306/order_db
      username: root
      password: root

jwt:
  secret: Y29tLm51Ymlmb3JtLnNwcmluZy1zZWN1cml0eS1yZXN0LWxvZ2luLThhNzlmODMzLTZjNjAtNGMzZS1hNWE1LTY0MjAxMzZlMTg2MQ==
  token-validity-in-second: 1800