spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc.swagger-ui.path: /swagger-ui.html

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.nubiform: debug

app:
  datasource:
    read-only:
      url: jdbc:mysql://localhost:3306/order_db
      username: readonly
      password: readonly

    write:
      url: jdbc:mysql://localhost:3306/order_db
      username: root
      password: root