spring:
  profiles:
    active: prod

  devtools:
    add-properties: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  redis:
    host: localhost
    port: 6379

springdoc.swagger-ui.path: /swagger-ui.html

app:
  datasource:
    read-only:
      url: jdbc:mysql://localhost:3306/order_db
      username: readonly
      password: readonly

    write:
      url: jdbc:mysql://localhost:3306/order_db
      username: root
      password: root

jwt:
  secret: T3JkZXJNYW5hZ2VtZW50UHJvamVjdHxjb20ubnViaWZvcm18b3JkZXItYmFja2VuZHw4YTc5ZjgzMy02YzYwLTRjM2UtYTVhNS02NDIwMTM2ZTE4NjE=
  token-validity-in-second: 1800