spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  redis:
    port: 16379

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.nubiform: debug

app:
  datasource:
    read-only:
      url: jdbc:h2:mem:testdb
      username: sa
      password: sa

    write:
      url: jdbc:h2:mem:testdb
      username: sa
      password: sa

jwt:
  token-validity-in-second: 3